INFO:root:@@@starting_test@@@
INFO:root:running solution in directory or
DEBUG:root:running test module for solution path ../solutions/ex1\or
DEBUG:root:grading <unittest.runner.TextTestResult run=8 errors=0 failures=0>, 5, {'test_fizzbuzz': 20, 'test_count_in_str': 30})
INFO:root:final score for ../solutions/ex1\or is 100
INFO:root:completed execution of solution in directory or
INFO:root:running solution in directory yosi
DEBUG:root:running test module for solution path ../solutions/ex1\yosi
INFO:root:Failed test description: test_fizzbuzz)
INFO:root:Failed test description: Test that the area of a circle with radius 1 is 3.14)
INFO:root:Failed test description: test_radius_10)
DEBUG:root:grading <unittest.runner.TextTestResult run=8 errors=0 failures=3>, 5, {'test_fizzbuzz': 20, 'test_count_in_str': 30})
DEBUG:root:failed: (<test_ex1.TestEx1 testMethod=test_fizzbuzz>, 'Traceback (most recent call last):\n  File "../testers/test_ex1\\test_ex1.py", line 28, in test_fizzbuzz\n    self.assertEqual(ex1.fizzbuzz(1),1)\nAssertionError: 2 != 1\n'), test_fizzbuzz
DEBUG:root:failed: (<test_ex1.TestEx1 testMethod=test_radius_1>, 'Traceback (most recent call last):\n  File "../testers/test_ex1\\test_ex1.py", line 21, in test_radius_1\n    self.assertEqual(ex1.circle_area(1),3.14)\nAssertionError: 3.1 != 3.14\n'), test_radius_1
DEBUG:root:failed: (<test_ex1.TestEx1 testMethod=test_radius_10>, 'Traceback (most recent call last):\n  File "../testers/test_ex1\\test_ex1.py", line 25, in test_radius_10\n    self.assertEqual(ex1.circle_area(10),314)\nAssertionError: 310.0 != 314\n'), test_radius_10
INFO:root:final score for ../solutions/ex1\yosi is 70
INFO:root:completed execution of solution in directory yosi
INFO:root:@@@finished_test@@@
